### ISSUE TITLE
defaultTimeRange: allow to use any int values

### ISSUE THREAD

**Issue by ildar170975** [SpangleLabs/history-explorer-card#16]
Consider the code:
```
type: custom:history-explorer-card
cardName: abcdef
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
defaultTimeRange: 20h
```
Seems that currently the value of `defaultTimeRange` is kind of "filtered".
For instance, instead of `20h` another value (`24h`) is used.

Managed to fix this locally by forced calling `setTimeRangeMinutes` in `setTimeRangeFromString`.
https://github.com/SpangleLabs/history-explorer-card/blob/f916a426227bed0926459045b5a667db44864751/src/history-explorer-card.js#L782
