### ISSUE TITLE
Line segment idea

### ISSUE THREAD

**Issue by Arkkimaagi** [SpangleLabs/history-explorer-card#20]
If I understood correctly based on [a forum post](https://community.home-assistant.io/t/under-new-management-interactive-history-explorer-custom-card/369450/1010), this card might use chart.js to render the charts.

I'd love if we could color line segments based on some criteria, so I could avoid having to color a separate timeline below the line segment.
![image](https://github.com/SpangleLabs/history-explorer-card/assets/1191667/b15a27db-2354-4974-87ea-8765a6024de8)

Currently I do it with this config:

```YAML
type: custom:history-explorer-card
cardName: historycard-39265679
header: Historia
defaultTimeRange: 24h
decimation: accurate
lineMode: stepped
lineGraphHeight: 500
barGraphHeight: 500
refresh:
  automatic: true
uiLayout:
  selector: hide
stateColors:
  poistaa: '#43a047'
  varo: '#ffa600'
  puhaltaa: '#db4437'
  virhe: '#039be5'
graphs:
  - type: line
    options: null
    entities:
      - entity: sensor.airflow_direction
        name: Airflow Direction
  - type: timeline
    entities:
      - entity: sensor.airflow_direction
        name: Airflow Direction
        process: |-
          ( state < 10 ) ? 
            "poistaa" : 
            ( state < 20) ?
              "varo" :
              ( state >= 20 ) ?
              "puhaltaa" : "virhe"
```

To me it seems that chart.js supports line segment coloring, so could there be a way to color the line based on similar rules?

https://www.chartjs.org/docs/latest/samples/line/segments.html
