### ISSUE TITLE
Wind bearing sensor format

### ISSUE THREAD

**Issue by roumano** [SpangleLabs/history-explorer-card#40]
Hi,

It's not a "real" bug but i don't known how to have help otherwise , ...

I'm trying to use it for Wind direction but maybe my sensor sensor doesn't have the data in good format to show it in `custom:history-explorer-card`

Can someone explain how the sensor should be format to be able to use this ? : 
```
type: custom:history-explorer-card
entityOptions:
  sensor.wind_bearing:      # This sensor should be shown as compass arrows instead of a line graph
    type: arrowline
    color: black            # Optional color for the arrows, remove for auto selection based on the theme
    fill: rgba(0,0,0,0.2)   # Optional background color for the arrows
```

**Comment by roumano** [comment]
Can someone help to understand what it's need to use the wind_bearing, please.

**Comment by ildar170975** [comment]
Smth like this?
```
type: custom:history-explorer-card
entityOptions:
  sensor.weather_home_gismeteo_wind_bearing:
    type: arrowline
    color: red
    fill: rgba(0,255,0,0.2)
graphs:
  - type: line
    entities:
      - entity: sensor.weather_home_gismeteo_wind_bearing
```

![Image](https://github.com/user-attachments/assets/d213b06a-44ee-4689-adc6-06a8b78d7030)

**Comment by roumano** [comment]
> sensor.weather_home_gismeteo_wind_bearing

Yes, how look like the sensor `sensor.weather_home_gismeteo_wind_bearing`, maybe i don't have good value, as i'm not able to have this kind of graph.
As it's a esphome device, i can easily update it but don't known exactly what i need

My sensor look like this : 

![Image](https://github.com/user-attachments/assets/3d97a252-60c8-495e-9528-3957ebfcb894)

And with your code, i'm able to have the graph but not the bearing

![Image](https://github.com/user-attachments/assets/427357f6-1d7f-4e8e-be58-2fa6e5c76e51)


( But i can use my sensor in the `type: custom:windrose-card` )

**Comment by ildar170975** [comment]
Honestly, have no idea how "arrows" are rendered.
There are unclear things.
Do not understand why arrows are different if a graph is a stepline.
Why 270 deg = arrow right?
![Image](https://github.com/user-attachments/assets/a92068c0-8a7d-404f-92f6-05e4cddf0677)

**Comment by roumano** [comment]
i'm sensor show 135° for South-South-Est, so for me it's not `270 deg = arrow right` : 

![Image](https://github.com/user-attachments/assets/b23cc482-79ef-47ad-9697-c9612ba9b98d)

for me, it's not showing any arrows in `history-explorer-card`

**Comment by ildar170975** [comment]
Have you tried with exactly my code (place own entity in 2 places)?

**Comment by roumano** [comment]
> wn entity in 2 places)?

Yes, exactly

![Image](https://github.com/user-attachments/assets/bf07e9b0-aecb-410c-9256-ae5969b161d2)

 the same code as you with only the sensor replacement in 2 places (i've use replace function on a texte editor twice to be sure, i'm not making any typo error) :

**Comment by ildar170975** [comment]
Funny, I lost the "arrows" panel by pressing a small "cross" button:
![Image](https://github.com/user-attachments/assets/411208d7-76bc-4191-a140-d0fa86fbdaa4)
No idea how to get it back))))

**Comment by roumano** [comment]
Create a new dashboard ;)

Otherwise, can you show me, your attributes (in Home Assistant) for your `sensor.weather_home_gismeteo_wind_bearing` sensor ?

**Comment by ildar170975** [comment]
> your attributes

![Image](https://github.com/user-attachments/assets/3d2bfb81-71f9-46a7-801f-b75ed43776d5)

> Create a new dashboard ;)

May be next time))) Not using the card so far... Just testing from time to time.

**Comment by BlackRockCity** [comment]
![Image](https://github.com/user-attachments/assets/c26a0e6b-f888-4c69-a3e6-0b77d9c7cf44)

```
type: custom:history-explorer-card
header: hide
timeframe: 24h
decimation: false
labelsVisible: false
showUnavailable: false
refresh:
  automatic: true
uiLayout:
  selector: hide
  toolbar: hide
uiColors:
  gridlines: rgba(180,0,0,0.2)
timeTicks:
  densityOverride: 'medium'
graphs:
  - type: arrowline
    title: Wind Direction
    entities:
      - entity: sensor.wind_direction
        color: red
        fill: rgba(180,0,0,0.1)
  - type: line
    entities:
      - entity: sensor.wind_direction
```

or just arrows:

![Image](https://github.com/user-attachments/assets/e9ec0502-a0d1-45d8-a55b-a49ccf01abd6)

```
type: custom:history-explorer-card
header: hide
timeframe: 24h
labelsVisible: false
showUnavailable: false
refresh:
  automatic: true
uiLayout:
  selector: hide
  toolbar: hide
uiColors:
  gridlines: 'none'
graphs:
  - type: arrowline
    title: Wind Direction
    entities:
      - entity: sensor.wind_direction
        color: red
        fill: rgba(180,0,0,0.1)
```

lineMode stepped:

![Image](https://github.com/user-attachments/assets/a1b1cba8-1599-4f6b-9311-ce184b65d5c3)

```
type: custom:history-explorer-card
header: hide
timeframe: 24h
decimation: false
labelsVisible: false
showUnavailable: false
refresh:
  automatic: true
uiLayout:
  selector: hide
  toolbar: hide
uiColors:
  gridlines: rgba(180,0,0,0.2)
timeTicks:
  densityOverride: medium
graphs:
  - type: arrowline
    title: Wind Direction
    entities:
      - entity: sensor.wind_direction
        color: red
        fill: rgba(180,0,0,0.1)
  - type: line
    entities:
      - entity: sensor.wind_direction
        lineMode: stepped
```
