### ISSUE TITLE
timeline popup menu appears partially only

### ISSUE THREAD

**Issue by Lutier2017** [SpangleLabs/history-explorer-card#51]
Hi, I configured a history-explorer-card in my HA to monitor 2 discrete values.

Initially, I configured separate entities.
No problem. see below photo.

![Image](https://github.com/user-attachments/assets/fbdafa08-257d-439d-9d72-7f109cc01f36)

The portion of the code for these 2 entities is:
```
graphs:
  - type: timeline
    entities:
      - entity: switch.ltsp_1_tr
  - type: timeline
    entities:
      - entity: timer.aut_ltsp_1_tr_pump_run_timer
        name: Timer
```

Later, to minimize space, I used the below code to configure the referred 2 entities together.
See below photo.

![Image](https://github.com/user-attachments/assets/8977af74-99d8-43e1-928f-55b9822b567d)

The portion of the code to configure the combined entities is:
```
graphs:
  - type: timeline
    entities:
      - entity: switch.ltsp_1_tr
      - entity: timer.aut_ltsp_1_tr_pump_run_timer
        name: Timer
```

Notice in the 2nd photo, the popup menu appears partially only, not full as in the first photo.

QUESTION:
Is there a way to solve this issue?

The full code for my history-explorer-card is:
```
type: custom:history-explorer-card
cardName: Test
showUnavailable: true
recordedEntitiesOnly: true
decimation: true
lineMode: stepped
refresh:
  interval: 30
graphs:
  - type: timeline
    entities:
      - entity: switch.ltsp_1_tr
  - type: timeline
    entities:
      - entity: timer.aut_ltsp_1_tr_pump_run_timer
        name: Timer
  - type: line
    entities:
      - entity: sensor.ltsp_1_tr_power
        name: Pump power
view_layout:
  grid-area: C43
```
